### PR TITLE
Web Time Machine MVP: Browser History Storage and Backend, Basic Search (iOS, Chrome) + Github Actions

### PR DESCRIPTION
**Pull request by eefh**
### Overview

Here's the current state of the project so far:

- Chrome extension as seen before

- Simple backend built with flask for receiving browser history. This backend handles incoming data from clients and organizes it for easy retrieval.

- Basic search functionality in the extension

- iOS Safari extension that sends essential browsing data (date/time, web page content, URLs) to the backend.

- Automated build and test of the iOS safari extension with Github Actions (this took me way longer than I expected, apologies for this.)
<hr/>

### Github Actions

**Build and Test Workflow** **(on push, PR)**

- Build and Test workflow setup for the iOS safari extension

**Release workflow** (on push tag) 
- Publish a release

### CODE REVIEW

**Comment by posix4e** [comment]
1) Please resolve and fix conflicts
2) Please make sure all images are added via git lfs, don't just check them in
3) Can you provide a moving screenshot of it in action on the README?
4) We should deploy the backend on merge to main to vercel or something.
5) We should have some tests to make sure the backend works right

**Review by posix4e — CHANGES_REQUESTED** [review]
Please resolve and fix conflicts
Please make sure all images are added via git lfs, don't just check them in
Can you provide a moving screenshot of it in action on the README?
We should deploy the backend on merge to main to vercel or something.
We should have some tests to make sure the backend works right

**Comment by eefh** [comment]
> Please resolve and fix conflicts Please make sure all images are added via git lfs, don't just check them in Can you provide a moving screenshot of it in action on the README? We should deploy the backend on merge to main to vercel or something. We should have some tests to make sure the backend works right

Awesome thanks for the feedback aiming to knock these out today also good ideas for the backend

**Comment by eefh** [comment]
> Please make sure all images are added via git lfs

Github has problems with using lfs with public forks so i'll have to find a workaround

**Comment by posix4e** [comment]
I added you as a collaborator. Please try pushing a branch to my repo

**Pull request merged**
